### ISSUE TITLE
查看節點訊息時有後端 PHP error

### ISSUE THREAD

**Issue by winwell** [sspanel-uim/Wiki#28]
```
Slim Application Error
The application could not run because of the following error:

Details
Type: ParseError
Message: syntax error, unexpected ','
File: /sspanel/src/Utils/AppURI.php
Line: 107
Trace
#0 /sspanel/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /sspanel/src/Utils/URL.php(356): spl_autoload_call()
#3 /sspanel/storage/framework/smarty/compile/2a2c8eb55b9e2131b08b1b87435d05ea7e8dc655_0.file.node_ss_ssr.tpl.php(74): App\Utils\URL::getItemUrl()
#4 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_60a51a3449d880_55248760()
#5 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#6 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#7 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#8 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#9 /sspanel/src/Controllers/User/NodeController.php(138): Smarty_Internal_TemplateBase->display()
#10 [internal function]: App\Controllers\User\NodeController->user_node_info()
#11 /sspanel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#12 /sspanel/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#13 /sspanel/src/Middleware/Auth.php(26): Slim\Route->__invoke()
#14 [internal function]: App\Middleware\Auth->__invoke()
#15 /sspanel/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#16 [internal function]: Slim\DeferredCallable->__invoke()
#17 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#18 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}()
#19 /sspanel/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#20 /sspanel/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#21 /sspanel/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke()
#22 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke()
#23 /sspanel/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#24 [internal function]: Slim\DeferredCallable->__invoke()
#25 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#26 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#27 /sspanel/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#28 /sspanel/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#29 /sspanel/public/index.php(37): Slim\App->run()
#30 {main}
```

src/Utils/AppURI.php  Line 107 串接字串多了一個分號
  > ? ', tls=true`'` ,sni=' . $item['host']

應改成
  > ? ', tls=true ,sni=' . $item['host']

**Comment by winwell** [comment]
轉發至 https://github.com/Anankke/SSPanel-Uim/issues/1259
